CREATE TABLE IF NOT EXISTS "Challenge30" (
  "userId" TEXT NOT NULL PRIMARY KEY REFERENCES "User"("id") ON DELETE CASCADE ON UPDATE CASCADE,
  "data" JSONB NOT NULL DEFAULT 'null',
  "revision" INTEGER NOT NULL DEFAULT 0,
  "aiDay" TEXT NOT NULL DEFAULT '',
  "aiCount" INTEGER NOT NULL DEFAULT 0,
  "pendingId" TEXT,
  "pendingAt" TIMESTAMP(3),
  "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP
);
