name: yeahdays
region: fra
services:
  - name: web
    github:
      repo: ayatyeah/YeahDays
      branch: master
      deploy_on_push: true
    source_dir: /
    dockerfile_path: /Dockerfile
    http_port: 80
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /

  - name: api
    github:
      repo: ayatyeah/YeahDays
      branch: master
      deploy_on_push: true
    source_dir: /server
    dockerfile_path: /server/Dockerfile
    http_port: 4000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb
    routes:
      - path: /api
        preserve_path_prefix: true
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "4000"
      - key: MONGODB_URI
        scope: RUN_AND_BUILD_TIME
        value: CHANGE_ME_MONGODB_URI
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        value: CHANGE_ME_JWT_SECRET
        type: SECRET
      - key: CLIENT_ORIGIN
        scope: RUN_AND_BUILD_TIME
        value: https://yeahdays-qk3jx.ondigitalocean.app
