const {PrismaClient}=require('@prisma/client');const {chromium,request}=require('playwright');const {randomUUID}=require('node:crypto');const assert=require('node:assert/strict');
(async()=>{if(!process.env.DATABASE_URL?.includes('yeahgrind_community_qa'))throw new Error('Isolated QA DB required');const db=new PrismaClient();const ids=[randomUUID(),randomUUID()].map(s=>'qa-access-'+s);let browser,ctx;const base=process.env.E2E_BASE||'http://localhost:3122';
try{for(const id of ids)await db.user.create({data:{id,name:'Access QA'}});await db.userState.create({data:{userId:ids[0],data:{todos:[{title:'Моя лабораторная по сетям',date:'2026-10-02',done:false,note:'SECRET_NOTES'}],plan:[{snapshot:{title:'Повторить TCP',duration:15},completed:false}],onboarded:true},clientAt:new Date()}});await db.userState.create({data:{userId:ids[1],data:{todos:[{title:'OTHER_ACCOUNT_SECRET',done:false}]},clientAt:new Date()}});
const {encode}=await import('@auth/core/jwt');const token=await encode({secret:'community-qa-secret',salt:'authjs.session-token',token:{id:ids[0],sub:ids[0],name:'QA'}});ctx=await request.newContext({baseURL:base,extraHTTPHeaders:{Cookie:'authjs.session-token='+token}});
assert.equal((await(await ctx.get('/api/ai/context')).json()).context,null);const preview=await(await ctx.get('/api/ai/context?scope=plan&userId='+ids[1])).json();assert.ok(JSON.stringify(preview).includes('Моя лабораторная'));assert.ok(JSON.stringify(preview).includes('Повторить TCP'));assert.ok(!JSON.stringify(preview).includes('SECRET'));assert.equal((await ctx.get('/api/ai/context?scope=password')).status(),400);
assert.equal((await ctx.post('/api/ai/chat',{data:{message:'Read my account',requestId:randomUUID(),withPlan:true}})).status(),400);
browser=await chromium.launch();const page=await browser.newPage({viewport:{width:390,height:844},serviceWorkers:'block'});await page.context().addCookies([{name:'authjs.session-token',value:token,url:base}]);await page.addInitScript(()=>localStorage.setItem('yeahdays-store',JSON.stringify({state:{onboarded:false,name:'QA'},version:13})));
// Keep unrelated onboarding/state synchronization out of this scoped test.
await page.route('**/api/state**',r=>r.fulfill({contentType:'application/json',body:JSON.stringify({data:null})}));
await page.goto(base+'/chat');await page.getByText('Доступ к данным YeahGrind выключен').waitFor();await page.getByRole('button',{name:'Разрешить доступ к данным',exact:true}).click();assert.equal(await page.getByRole('checkbox').count(),4);for(const c of await page.getByRole('checkbox').all())assert.equal(await c.isChecked(),false);assert.equal(await page.getByRole('button',{name:'Разрешаю передать выбранные данные'}).isEnabled(),false);
await page.getByRole('checkbox').first().check();await page.getByRole('button',{name:'Посмотреть, какие данные будут переданы'}).click();await page.locator('pre').filter({hasText:'Моя лабораторная'}).waitFor();await page.getByRole('button',{name:'Разрешаю передать выбранные данные'}).click();await page.getByText('Доступ разрешён для следующего сообщения').waitFor();await page.getByRole('button',{name:'Снять разрешение'}).click();await page.getByText('Доступ к данным YeahGrind выключен').waitFor();
await page.getByRole('button',{name:'Разрешить доступ к данным',exact:true}).click();await page.getByRole('checkbox').first().check();await page.getByRole('button',{name:'Разрешаю передать выбранные данные'}).click();
if(process.env.QA_LIVE_AI==='1'){await page.getByLabel('Сообщение ИИ').fill('Назови мою незавершённую лабораторную из переданного снимка. Ответь только её названием.');await page.getByRole('button',{name:'Отправить',exact:true}).click();await page.locator('[aria-label="История переписки"] article').nth(1).waitFor({timeout:90000});await page.getByText('Доступ к данным YeahGrind выключен').waitFor();const row=await db.aiChat.findUnique({where:{userId:ids[0]}});assert.equal(row.messages.length,2);assert.deepEqual(row.messages[0].access.scopes,['plan']);assert.deepEqual(row.messages[1].access.scopes,['plan']);assert.ok(row.messages[1].text.toLowerCase().includes('сет'));console.log('PASS real AI uses consented task context; consent resets after send');}
await page.setViewportSize({width:320,height:800});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await page.screenshot({path:'/tmp/ai-consent.png',fullPage:true});console.log('PASS default-deny, explicit scope confirmation, preview isolation/redaction, legacy rejection, revoke, mobile UI');
}finally{if(browser)await browser.close();if(ctx)await ctx.dispose();await db.user.deleteMany({where:{id:{in:ids}}});await db.$disconnect();}})().catch(e=>{console.error(e);process.exitCode=1});
