'use client';
import { useCallback, useEffect, useRef, useState, type FormEvent, type ReactNode } from 'react';
import { useSession } from 'next-auth/react';
import Link from 'next/link';
import Modal from '@/components/ui/Modal';
import FriendsCard from '@/components/FriendsCard';
import type { communityHome, teamView, publicProfile } from '@/lib/communityDb';
import { focusRequired } from '@/lib/community';
type Home = Awaited<ReturnType<typeof communityHome>>;
type Team = Awaited<ReturnType<typeof teamView>>;
type Profile = Awaited<ReturnType<typeof publicProfile>>;
type Act = (data: Record<string, unknown>) => Promise<boolean>;
const field = 'w-full min-w-0 rounded-xl border border-[var(--color-border-strong)] bg-[var(--color-surface-2)] px-3 py-2.5 text-base';
const button = 'min-h-11 rounded-xl bg-[var(--color-intelligence)] px-4 py-2 text-sm font-semibold text-[var(--color-bg)] disabled:opacity-50';
const secondary = 'min-h-11 rounded-xl border border-[var(--color-border-strong)] px-3 py-2 text-sm disabled:opacity-50';
const card = 'rounded-2xl border border-[var(--color-border)] bg-[var(--color-surface)] p-4';
function Field({ title, children }: { title: string; children: ReactNode }) { return <label className="grid gap-1.5 text-sm">{title}{children}</label>; }
async function api(query = '', body?: Record<string, unknown>) {
  const res = await fetch('/api/community'+query, { method: body ? 'POST' : 'GET', headers: body ? { 'Content-Type': 'application/json' } : undefined, body: body ? JSON.stringify(body) : undefined, cache: 'no-store' });
  const data = await res.json(); if(!res.ok) throw new Error(data.error || 'Не удалось загрузить данные'); return data;
}
function values(event: FormEvent<HTMLFormElement>) { event.preventDefault(); return Object.fromEntries(new FormData(event.currentTarget).entries()); }
export default function CommunityPage() {
  const { data, status } = useSession();
  if(status==='loading') return <p role="status">Открываем сообщество…</p>;
  if(!data?.user?.id) return <Link href="/login">Войди, чтобы учиться вместе</Link>;
  return <Community key={data.user.id} />;
}
function Community() {
  const [home,setHome]=useState<Home|null>(null); const [team,setTeam]=useState<Team|null>(null);
  const [selected,setSelected]=useState(''); const [tab,setTab]=useState('teams'); const [error,setError]=useState(''); const [notice,setNotice]=useState(''); const [busy,setBusy]=useState(false);
  const [invite,setInvite]=useState(''); const [profile,setProfile]=useState<Profile|null>(null); const [profileError,setProfileError]=useState('');
  const busyRef=useRef(false);
  const alive=useRef(true); const sequence=useRef(0);
  useEffect(()=>{alive.current=true; const q=new URLSearchParams(location.search);setInvite(q.get('join')||'');if(q.get('profile'))void viewProfile(q.get('profile')!);return()=>{alive.current=false;sequence.current++;};},[]);
  const load=useCallback(async()=>{const n=++sequence.current;try{const [h,t]=await Promise.all([api(),selected?api('?team='+encodeURIComponent(selected)):null]);if(alive.current&&n===sequence.current){setHome(h);setTeam(t);setError('');}}catch(e){if(alive.current&&n===sequence.current)setError((e as Error).message);}},[selected]);
  useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==='visible')void load();},15000);return()=>clearInterval(timer);},[load]);
  const act:Act=async data=>{if(busyRef.current)return false;busyRef.current=true;setBusy(true);setError('');setNotice('');try{const result=await api('',{teamId:selected,...data});if(!alive.current)return false;
    if(result.teamId){setSelected(result.teamId);setInvite('');history.replaceState(null,'','/community');}
    else if(data.action==='leave'||data.action==='deleteTeam'){setSelected('');setTeam(null);}
    else await load();setNotice('Готово');return true;
  }catch(e){if(alive.current)setError((e as Error).message);return false;}finally{busyRef.current=false;if(alive.current)setBusy(false);}};
  async function viewProfile(id:string){setProfile(null);setProfileError('');try{const p=await api('?profile='+encodeURIComponent(id));if(alive.current)setProfile(p);}catch(e){if(alive.current)setProfileError((e as Error).message);}}
  return <main className="mx-auto w-full max-w-3xl space-y-5 pb-4">
    <header><p className="text-sm text-[var(--color-intelligence)]">Учиться легче вместе</p><h1 className="mt-1 text-3xl font-bold">Сообщество</h1><p className="mt-2 text-sm text-[var(--color-fg-dim)]">Своя команда, общие цели и помощь по предметам.</p></header>
    <div className="flex gap-2" aria-label="Разделы сообщества">{[['teams','Команды'],['friends','Друзья'],['profile','Мой профиль']].map(([id,label])=><button key={id} className={tab===id?button:secondary} onClick={()=>{setTab(id);setProfile(null);setProfileError('');}} aria-pressed={tab===id}>{label}</button>)}</div>
    {error&&<div role="alert" className={card+' text-[var(--color-strength)]'}>{error} <button className="underline" onClick={()=>void load()}>Повторить</button></div>}
    {notice&&<p role="status" className="text-sm text-[var(--color-stability)]">{notice}</p>}
    {!home&&!error&&<p role="status">Загружаем команды…</p>}
    {home&&tab==='friends'&&<><FriendsCard/><p className="text-sm text-[var(--color-fg-dim)]">Поделись приглашением из карточки друзей. Для занятий создайте команду и отправьте её отдельную ссылку.</p></>}
    {home&&tab==='profile'&&<><ProfileEditor home={home} act={act} busy={busy}/><button className={secondary} onClick={()=>void viewProfile(home.userId)}>Посмотреть мой профиль</button>{!!home.profile?.blocked.length&&<section className={card}><h2 className="font-semibold">Заблокированные</h2>{home.profile.blocked.map((id,i)=><div key={id} className="mt-2 flex items-center justify-between"><span>Пользователь {i+1}</span><button className={secondary} disabled={busy} onClick={()=>void act({action:'unblock',userId:id})}>Разблокировать</button></div>)}</section>}</>}
    {home&&tab==='teams'&&<>
      {invite&&<form className={card+' space-y-3'} onSubmit={e=>{e.preventDefault();void act({action:'join',invite});}}><h2 className="font-semibold">Тебя пригласили в команду</h2><p className="text-sm">После вступления участники увидят твоё имя. Твои задачи и LMS останутся приватными.</p><button className={button} disabled={busy}>Присоединиться</button><button type="button" className={secondary+' ml-2'} onClick={()=>{setInvite('');history.replaceState(null,'','/community');}}>Не сейчас</button></form>}
      <div className="flex flex-wrap gap-2">{home.teams.map(t=><button className={selected===t.id?button:secondary} disabled={busy} key={t.id} onClick={()=>{setSelected(t.id);setTeam(null);}}>{t.name} <span className="opacity-60">· {t._count.members}</span></button>)}</div>
      {!selected&&<section className={card+' space-y-3'}><h2 className="text-lg font-semibold">{home.teams.length?'Выбери команду':'Собери свою первую команду'}</h2><p className="text-sm text-[var(--color-fg-dim)]">Например, «Готовимся к Networks». Пригласи одногруппников, задай общий квест и включите таймер вместе.</p></section>}
      <details className={card}><summary className="cursor-pointer font-semibold">Создать команду или ввести приглашение</summary><form className="mt-4 grid gap-3" onSubmit={async e=>{const f=e.currentTarget;const data=values(e);if(await act({action:'create',...data}))f.reset();}}><Field title="Название команды"><input name="name" required maxLength={80} placeholder="Готовимся к экзамену" className={field}/></Field><Field title="Предмет"><input name="subject" required maxLength={100} placeholder="Computer Networks" className={field}/></Field><button className={button} disabled={busy}>Создать закрытую команду</button></form><form className="mt-5 grid gap-3" onSubmit={e=>{const data=values(e);let code=String(data.invite).trim();try{code=new URL(code).searchParams.get('join')||code;}catch{}void act({action:'join',invite:code});}}><Field title="Ссылка или код приглашения"><input name="invite" className={field} required/></Field><button className={secondary} disabled={busy}>Вступить</button></form></details>
      {selected&&!team&&!error&&<p role="status">Открываем команду…</p>}
      {team&&home&&<TeamPanel key={team.id} team={team} me={home.userId} act={act} busy={busy} ai={home.available} onProfile={viewProfile}/>}
    </>}
    <Modal open={!!profile||!!profileError} onClose={()=>{setProfile(null);setProfileError('');}} title="Профиль студента">
    {profileError&&<p role="status">{profileError}</p>}
    {profile&&<section className={card+' space-y-3'}><div className="flex justify-between"><h2 className="text-xl font-bold">{profile.name}</h2><button className={secondary} onClick={()=>setProfile(null)}>Закрыть</button></div>{profile.character&&<img src={profile.character} alt="Персонаж студента" className="mx-auto h-44 object-contain"/>}<p className="whitespace-pre-wrap break-words">{profile.bio}</p><h3 className="font-semibold">Предметы</h3><p>{profile.subjects.join(' · ')||'Пока не указаны'}</p><h3 className="font-semibold">Публичные цели</h3><ul className="list-inside list-disc">{profile.goals.map(g=><li key={g}>{g}</li>)}</ul>{profile.sessions!==null&&<p>Завершено совместных занятий: {profile.sessions}</p>}{profile.badge&&<p className="text-[var(--color-intelligence)]">✦ {profile.badge}</p>}{profile.userId!==home?.userId&&<button className={secondary} disabled={busy} onClick={async()=>{if(confirm('Скрыть ваши публикации друг от друга и удалить дружбу?')&&await act({action:'block',userId:profile.userId}))setProfile(null);}}>Заблокировать</button>}</section>}
    </Modal>
  </main>;
}
function ProfileEditor({home,act,busy}:{home:Home;act:Act;busy:boolean}) {
  const p=home.profile;
  return <form className={card+' grid gap-4'} onSubmit={e=>{const d=values(e);void act({action:'profile',bio:d.bio,subjects:String(d.subjects).split('\n').map(s=>s.trim()).filter(Boolean),goals:String(d.goals).split('\n').map(s=>s.trim()).filter(Boolean),published:d.published==='on',showCharacter:d.showCharacter==='on',showAchievements:d.showAchievements==='on'});}}>
    <h2 className="text-lg font-semibold">Что увидят другие</h2><p className="text-sm text-[var(--color-fg-dim)]">Публичный профиль доступен вошедшим пользователям. Личный план, посещаемость и переписка с ИИ сюда не попадают.</p>
    <Field title="О себе"><textarea className={field} name="bio" maxLength={500} defaultValue={p?.bio}/></Field>
    <Field title="Предметы — по одному на строку, до 8"><textarea className={field} name="subjects" defaultValue={p?.subjects.join('\n')} placeholder="Computer Networks"/></Field>
    <Field title="Цели, которыми хочешь поделиться — до 8"><textarea className={field} name="goals" defaultValue={p?.goals.join('\n')} placeholder="Разобраться в маршрутизации"/></Field>
    <label className="flex gap-3"><input type="checkbox" name="showCharacter" defaultChecked={p?.showCharacter}/>Показывать мой скин</label><label className="flex gap-3"><input type="checkbox" name="showAchievements" defaultChecked={p?.showAchievements}/>Показывать совместные занятия и значок</label><label className="flex gap-3"><input type="checkbox" name="published" defaultChecked={p?.published}/>Опубликовать профиль</label><button className={button} disabled={busy}>Сохранить видимость</button>
  </form>;
}
function TeamPanel({team,me,act,busy,ai,onProfile}:{team:Team;me:string;act:Act;busy:boolean;ai:boolean;onProfile:(id:string)=>void}) {
  const [tab,setTab]=useState('feed');const [copy,setCopy]=useState('');const owner=team.ownerId===me;
  return <section className="space-y-4"><header className={card}><p className="text-sm text-[var(--color-intelligence)]">{team.subject}</p><h2 className="mt-1 text-2xl font-bold break-words">{team.name}</h2><p className="mt-2 text-sm">Закрытая команда · {team.members.length} участников</p>{team.invite&&<details className="mt-3"><summary className="cursor-pointer">Пригласить одногруппников</summary><input aria-label="Приглашение в команду" readOnly className={field+' mt-3'} value={typeof location==='undefined'?'':location.origin+'/community?join='+team.invite}/><div className="mt-2 flex flex-wrap gap-2"><button className={secondary} onClick={async()=>{try{await navigator.clipboard.writeText(location.origin+'/community?join='+team.invite);setCopy('Ссылка скопирована');}catch{setCopy('Выдели и скопируй ссылку из поля выше');}}}>Скопировать</button><button className={secondary} disabled={busy} onClick={()=>{if(confirm('Старая ссылка перестанет работать. Обновить?'))void act({action:'rotate'});}}>Обновить ссылку</button></div><p role="status" className="text-sm">{copy}</p></details>}</header>
    <div className="grid grid-cols-4 gap-1">{[['feed','Лента'],['quests','Квесты'],['focus','Фокус'],['people','Люди']].map(([id,label])=><button key={id} className={tab===id?button:secondary} aria-pressed={tab===id} onClick={()=>setTab(id)}>{label}</button>)}</div>
    {tab==='feed'&&<><form className={card+' grid gap-3'} onSubmit={async e=>{const f=e.currentTarget;const data=values(e);if(await act({action:'post',...data}))f.reset();}}><h3 className="font-semibold">Чем поделишься?</h3><Field title="Тип публикации"><select name="kind" className={field}><option value="question">Вопрос по предмету</option><option value="resource">Полезный материал</option><option value="progress">Мой результат</option></select></Field><textarea name="text" aria-label="Текст публикации" required maxLength={4000} rows={3} className={field} placeholder="Что не получается? Или что сегодня понял?"/><p className="text-xs text-[var(--color-fg-dim)]">Увидят только участники команды. Ссылку на материал можно вставить в текст.</p><button className={button} disabled={busy}>Опубликовать</button></form>{!team.posts.length&&<p className={card}>Здесь пока тихо. Задай первый вопрос или поделись полезной ссылкой.</p>}{team.posts.map(p=><Post key={p.id} post={p} me={me} owner={owner} act={act} busy={busy} ai={ai} onProfile={onProfile}/>)}</>}
    {tab==='quests'&&<><p className="text-sm text-[var(--color-fg-dim)]">Один участник, завершивший комнату, приносит одно занятие в общий квест. Для зачёта нужно провести в комнате 80% времени и записать итог. Награда — значок «Командный прорыв» в квесте для его участников.</p>{team.quests.map(q=><article key={q.id} className={card+' space-y-2'}><h3 className="font-semibold">{q.title}</h3><p>{q.progress} / {q.target} совместных занятий</p><div role="progressbar" aria-label="Прогресс квеста" aria-valuenow={Math.min(q.progress,q.target)} aria-valuemin={0} aria-valuemax={q.target} className="h-2 overflow-hidden rounded-full bg-[var(--color-surface-2)]"><div className="h-full rounded-full bg-[var(--color-intelligence)]" style={{width:`${Math.min(100,q.progress/q.target*100)}%`}}/></div><p className="text-xs">До {new Date(q.deadline).toLocaleDateString('ru-RU')}{new Date(q.deadline).getTime()<Date.now()?' · Завершён':''}</p>{q.earned&&<p className="text-[var(--color-intelligence)]">✦ Твой значок: Командный прорыв</p>}<button className={secondary} onClick={()=>setTab('focus')}>Открыть комнаты фокуса</button></article>)}{!team.quests.length&&<p className={card}>Пока нет квестов. Организатор может задать первую общую цель.</p>}{owner&&<form className={card+' grid gap-3'} onSubmit={async e=>{const f=e.currentTarget;const d=values(e);if(await act({action:'quest',...d}))f.reset();}}><h3 className="font-semibold">Общий учебный квест</h3><Field title="Чему научимся"><input name="title" className={field} required maxLength={140} placeholder="Разобраться в TCP/IP"/></Field><Field title="Сколько занятий на всю команду"><input type="number" name="target" min={1} max={100} defaultValue={3} className={field}/></Field><Field title="Срок в днях"><input type="number" name="days" min={1} max={30} defaultValue={7} className={field}/></Field><button className={button} disabled={busy}>Создать квест</button></form>}</>}
    {tab==='focus'&&<Focus team={team} me={me} act={act} busy={busy}/>}
    {tab==='people'&&<><section className={card}><h3 className="font-semibold">Участники</h3>{team.members.map(m=><div key={m.userId} className="flex flex-wrap items-center justify-between gap-2 py-2"><button className="min-h-11 text-left underline" onClick={()=>onProfile(m.userId)}>{m.user.name||'Студент'}{m.userId===team.ownerId?' · организатор':''}</button>{m.userId!==me&&<button className={secondary} disabled={busy} onClick={()=>{if(confirm('Скрыть публикации этого участника и удалить дружбу?'))void act({action:'block',userId:m.userId});}}>Блокировать</button>}</div>)}</section>{owner&&<section className={card+' space-y-3'}><h3 className="font-semibold">Жалобы на публикации</h3>{!team.reports.length&&<p className="text-sm">Новых жалоб нет.</p>}{team.reports.map(r=><div key={r.id} className="space-y-2 border-t border-[var(--color-border)] pt-3"><p><strong>Причина:</strong> {r.reason}</p><RichText text={r.post.text}/><div className="flex flex-wrap gap-2"><button className={secondary} disabled={busy} onClick={()=>void act({action:'deletePost',postId:r.postId})}>Удалить публикацию</button><button className={secondary} disabled={busy} onClick={()=>void act({action:'resolve',reportId:r.id})}>Оставить публикацию</button></div></div>)}</section>}<button className={secondary+' text-[var(--color-strength)]'} disabled={busy} onClick={()=>{if(confirm(owner?'Удалить команду, ленту, квесты и комнаты для всех?':'Выйти из команды? Твои публикации останутся, их можно удалить до выхода.'))void act({action:owner?'deleteTeam':'leave'});}}>{owner?'Удалить команду':'Выйти из команды'}</button></>}
  </section>;
}
function RichText({text}:{text:string}) { return <p className="whitespace-pre-wrap break-words text-sm leading-relaxed">{text.split(/(https?:\/\/[^\s]+)/g).map((part,i)=>/^https?:\/\//.test(part)?<a key={i} className="underline text-[var(--color-intelligence)]" href={part} target="_blank" rel="noopener noreferrer nofollow">{part}</a>:part)}</p>; }
function Post({post:p,me,owner,act,busy,ai,onProfile}:{post:Team['posts'][number];me:string;owner:boolean;act:Act;busy:boolean;ai:boolean;onProfile:(id:string)=>void}) {
  const [report,setReport]=useState(false);
  return <article className={card+' space-y-3'}><div className="flex items-center justify-between gap-2"><button className="min-h-11 font-semibold underline" onClick={()=>onProfile(p.userId)}>{p.user.name||'Студент'}</button><span className="text-xs text-[var(--color-fg-dim)]">{p.kind==='question'?'Вопрос':p.kind==='resource'?'Материал':'Результат'}</span></div><RichText text={p.text}/><time className="block text-xs text-[var(--color-fg-dim)]">{new Date(p.createdAt).toLocaleString('ru-RU')}</time><div className="flex flex-wrap gap-2">
    {p.userId===me&&ai&&!p.replies.some(r=>r.ai)&&<button className={secondary} disabled={busy} onClick={()=>{if(confirm('Отправить текст этой публикации в OpenAI? Ответ увидит команда. Чужие комментарии и личный план не передаются.'))void act({action:'ai',postId:p.id});}}>✦ Попросить ИИ объяснить</button>}
    {(p.userId===me||owner)&&<button className={secondary} disabled={busy} onClick={()=>{if(confirm('Удалить публикацию и ответы?'))void act({action:'deletePost',postId:p.id});}}>Удалить</button>}{p.userId!==me&&<button className={secondary} onClick={()=>setReport(v=>!v)}>Пожаловаться</button>}</div>
    {report&&<form className="grid gap-2" onSubmit={async e=>{const d=values(e);if(await act({action:'report',postId:p.id,reason:d.reason}))setReport(false);}}><input name="reason" aria-label="Причина жалобы" className={field} required maxLength={500} placeholder="Что нарушает правила?"/><p className="text-xs">Жалобу получит организатор. Если жалоба на организатора — заблокируй его и напиши по контакту в политике.</p><button className={secondary} disabled={busy}>Отправить жалобу</button></form>}
    <div className="space-y-3 border-l-2 border-[var(--color-border-strong)] pl-3">{p.replies.map(r=><div key={r.id} className="space-y-1"><p className="text-xs font-semibold">{r.ai?'✦ ИИ-помощник · ответ может содержать ошибки':r.user.name||'Студент'}</p><RichText text={r.text}/>{(r.userId===me||owner)?<button className="min-h-11 text-xs underline" disabled={busy} onClick={()=>{if(confirm('Удалить ответ?'))void act({action:'deletePost',postId:r.id});}}>Удалить ответ</button>:<button className="min-h-11 text-xs underline" disabled={busy} onClick={()=>{const reason=prompt('Причина жалобы на ответ');if(reason)void act({action:'report',postId:r.id,reason});}}>Пожаловаться</button>}</div>)}</div>
    <form className="flex gap-2" onSubmit={async e=>{const f=e.currentTarget;const d=values(e);if(await act({action:'post',parentId:p.id,text:d.text}))f.reset();}}><input name="text" aria-label="Комментарий" className={field} maxLength={4000} required placeholder="Помоги с объяснением…"/><button className={secondary+' shrink-0'} disabled={busy}>Ответить</button></form>
  </article>;
}
function Focus({team,me,act,busy}:{team:Team;me:string;act:Act;busy:boolean}) {
  const [now,setNow]=useState(Date.now());const [active,setActive]=useState('');const [pulseError,setPulseError]=useState('');
  const offset=new Date(team.serverNow).getTime()-Date.now();const offsetRef=useRef(offset);useEffect(()=>{offsetRef.current=offset;},[team.serverNow]);
  useEffect(()=>{const t=setInterval(()=>setNow(Date.now()+offsetRef.current),1000);return()=>clearInterval(t);},[]);
  useEffect(()=>{if(!active)return;const t=setInterval(()=>{if(document.visibilityState==='visible')void api('',{action:'pulse',teamId:team.id,roomId:active}).then(()=>setPulseError('')).catch(()=>setPulseError('Не удалось подтвердить участие. Проверь соединение — это время может не засчитаться.'));},15000);return()=>clearInterval(t);},[active,team.id]);
  return <div className="space-y-4">{pulseError&&<p role="status" className="text-sm text-[var(--color-strength)]">{pulseError}</p>}<p className="text-sm text-[var(--color-fg-dim)]">Общий таймер идёт для всех одинаково. Нажми «Учусь здесь» и оставь комнату открытой. Активность отмечается, пока вкладка видна; таймер продолжится и после перезагрузки.</p><form className={card+' grid gap-3'} onSubmit={async e=>{const f=e.currentTarget;const d=values(e);if(await act({action:'room',...d}))f.reset();}}><Field title="Над чем работаем"><input name="title" className={field} required maxLength={100} placeholder="Разбираем третью лабораторную"/></Field><Field title="Длительность"><select name="minutes" className={field}><option value="25">25 минут</option><option value="15">15 минут</option><option value="50">50 минут</option></select></Field><Field title="Вклад в квест"><select name="questId" className={field}><option value="">Без квеста</option>{team.quests.filter(q=>new Date(q.deadline).getTime()>now).map(q=><option key={q.id} value={q.id}>{q.title}</option>)}</select></Field><button className={button} disabled={busy}>Создать комнату</button></form>
    {team.rooms.map(r=>{const remaining=Math.max(0,Math.ceil((new Date(r.endsAt).getTime()-now)/1000));const p=r.participants.find(p=>p.userId===me);const chat=team.chat.filter(c=>c.roomId===r.id);const required=focusRequired(new Date(r.startsAt),new Date(r.endsAt));return <article key={r.id} className={card+' space-y-3'}><h3 className="text-lg font-semibold">{r.title}</h3><p className="text-4xl font-semibold tabular-nums" aria-label="Осталось времени">{String(Math.floor(remaining/60)).padStart(2,'0')}:{String(remaining%60).padStart(2,'0')}</p><p className="text-xs">{r.participants.filter(p=>!p.completedAt&&now-new Date(p.lastSeenAt).getTime()<90000&&remaining>0).length} учатся · {r.participants.filter(p=>p.completedAt).length} завершили</p>{remaining>0&&!p?.completedAt&&<button className={active===r.id?secondary:button} disabled={busy||active===r.id} onClick={async()=>{if(await act({action:'enter',roomId:r.id}))setActive(r.id);}}>{active===r.id?'Ты учишься здесь':p?'Продолжить участие':'Учусь здесь'}</button>}{p&&<p className="text-xs">Учтено {Math.floor(p.seconds/60)} мин. из необходимых {Math.ceil(required/60)} мин.</p>}
      {!remaining&&p&&!p.completedAt&&(p.seconds>=required?<form className="grid gap-2" onSubmit={e=>{const d=values(e);void act({action:'finish',roomId:r.id,summary:d.summary});}}><Field title="Что удалось понять или сделать?"><textarea name="summary" className={field} required maxLength={500}/></Field><p className="text-xs">Итог увидят участники команды.</p><button className={button} disabled={busy}>Завершить и записать итог</button></form>:<p className="text-sm">Для зачёта не хватило времени участия. Присоединяйся к следующей комнате с самого начала.</p>)}
      {r.participants.filter(p=>p.completedAt).map(p=><p key={p.userId} className="text-sm"><strong>{team.members.find(m=>m.userId===p.userId)?.user.name||'Участник'}:</strong> {p.summary}</p>)}
      <details><summary className="min-h-11 cursor-pointer py-2">Чат комнаты · {chat.length}</summary><div className="max-h-64 space-y-3 overflow-y-auto py-2">{chat.map(c=><div key={c.id}><p className="text-xs font-semibold">{c.user.name||'Участник'}</p><RichText text={c.text}/>{(c.userId===me||team.ownerId===me)?<button className="min-h-11 text-xs underline" disabled={busy} onClick={()=>void act({action:'deletePost',postId:c.id})}>Удалить</button>:<button className="min-h-11 text-xs underline" disabled={busy} onClick={()=>{const reason=prompt('Причина жалобы');if(reason)void act({action:'report',postId:c.id,reason});}}>Пожаловаться</button>}</div>)}</div><form className="flex gap-2" onSubmit={async e=>{const f=e.currentTarget;const d=values(e);if(await act({action:'post',roomId:r.id,text:d.text}))f.reset();}}><input className={field} name="text" aria-label="Сообщение в комнате" required maxLength={4000} placeholder="Короткое сообщение…"/><button className={secondary} disabled={busy}>Отправить</button></form></details>
    </article>;})}
  </div>;
}
